### ISSUE TITLE
[fail to install] npm install verify-rsa-jwt-cloudflare-worker

### ISSUE THREAD

**Issue by taro-ishihara** [wataruoguchi/verify-rsa-jwt-cloudflare-worker#2]
failed with `npm install verify-rsa-jwt-cloudflare-worker`

npm ERR! command failed
npm ERR! command sh -c lefthook install
npm ERR! sh: lefthook: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tishihara/.npm/_logs/2023-08-29T22_37_10_598Z-debug-0.log

**Comment by wataruoguchi** [comment]
@taro-ishihara Thanks for reporting the issue! I removed the `post-install` command that caused the issue.
Please try installing it again, the version number is `1.0.5`. Please let me know if the problem persists.
