### ISSUE TITLE
Allow no caching with a null kv store

### ISSUE THREAD

**Issue by Soviut** [wataruoguchi/verify-rsa-jwt-cloudflare-worker#6]
In some cases I don't need to cache the JWKS. It would be nice to be able to set the kvstore option to null.

**Comment by wataruoguchi** [comment]
@Soviut Did you give `useKVStore` an `undefined`? I believe it's optional.

**Comment by Soviut** [comment]
I did not know that was possible. I was looking at the source but didn't think to look at the `useKVStore()` itself, only the `getJwks()`  which made it seem like a valid KV store was a requirement.

That should definitely be documented.

It also seems like a test case might be necessary since all the tests receive a namespace in the beforeEach.

**Comment by wataruoguchi** [comment]
@Soviut Please let me know if it works. Your PR for documentation/tests is welcome!

**Comment by Soviut** [comment]
@wataruoguchi I just tried and this works.

```typescript
  const jwks = await getJwks(
    'https://<myurl>/.well-known/jwks.json',
    useKVStore() // no cache
  )
```

I'll see about doing a PR to add the documentation for this. The test I'm less sure about.

Something I'd suggest is making the requirement for a kvstore in `getJwks()` optional as well. I feel like a kvstore cache is something you'd want to explicitly configure. Thoughts?

**Comment by wataruoguchi** [comment]
@Soviut Great idea! I will approve that idea if you add it in the PR 👍

**Comment by Soviut** [comment]
@wataruoguchi I've made a documentation PR. I'll see if I can do the other suggestion as a separate PR.

**Comment by wataruoguchi** [comment]
Hello @Soviut ! I hope you are doing well. I just published v.1.1.6 - including your request to make the second parameter optional. Now it simply be:

```ts
const jwks = await getJwks('https://<myurl>/.well-known/jwks.json')
```

Cheers 🍻
